// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/HUD/HudRaceResults.layout

class UDR_HudRaceResultsWidgets
{
	static const ResourceName s_sLayout = "{CA0A077D9BCB5060}UI/HUD/HudRaceResults.layout";
	ResourceName GetLayout() { return s_sLayout; }

	VerticalLayoutWidget m_PlayerList;

	bool Init(Widget root)
	{
		m_PlayerList = VerticalLayoutWidget.Cast(root.FindWidget("PanelSize.Overlay0.VerticalLayout0.m_PlayerList"));

		return true;
	}
}
