// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/HUD/HudSpectator.layout

class UDR_HudSpectatorWidgets
{
	static const ResourceName s_sLayout = "{ECE19D6F64222867}UI/HUD/HudSpectator.layout";
	ResourceName GetLayout() { return s_sLayout; }

	TextWidget m_LapCountText;

	TextWidget m_PositionText;

	TextWidget m_PlayerNameText;

	bool Init(Widget root)
	{
		m_LapCountText = TextWidget.Cast(root.FindWidget("RaceProgressPanel.Panel.VerticalLayout0.HudLineLap.TextRight"));

		m_PositionText = TextWidget.Cast(root.FindWidget("RaceProgressPanel.Panel.VerticalLayout0.HudLinePos.TextRight"));

		m_PlayerNameText = TextWidget.Cast(root.FindWidget("VerticalLayout0.HorizontalLayout0.PlayerName"));

		return true;
	}
}
