// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/HUD/HudRaceResults/RaceResultsPlayerLine.layout

class UDR_RaceResultsPlayerLineWidgets
{
	static const ResourceName s_sLayout = "{D5D73EF5847A7B0F}UI/HUD/HudRaceResults/RaceResultsPlayerLine.layout";
	ResourceName GetLayout() { return s_sLayout; }

	TextWidget m_PositionText;

	TextWidget m_PlayerNameText;

	TextWidget m_TimeText;

	bool Init(Widget root)
	{
		m_PositionText = TextWidget.Cast(root.FindWidget("HorizontalLayout0.m_PositionText"));

		m_PlayerNameText = TextWidget.Cast(root.FindWidget("HorizontalLayout0.m_PlayerNameText"));

		m_TimeText = TextWidget.Cast(root.FindWidget("HorizontalLayout0.m_TimeText"));

		return true;
	}
}
