// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/Lobby/PlayerLine.layout

class UDR_PlayerLineWidgets
{
	static const ResourceName s_sLayout = "{CAA1C1C8D8023792}UI/Lobby/PlayerLine.layout";
	ResourceName GetLayout() { return s_sLayout; }

	TextWidget m_PositionText;

	TextWidget m_PlayerNameText;

	TextWidget m_BestLapText;

	TextWidget m_CurrentLapText;

	bool Init(Widget root)
	{
		m_PositionText = TextWidget.Cast(root.FindWidget("HorizontalLayout0.m_PositionText"));

		m_PlayerNameText = TextWidget.Cast(root.FindWidget("HorizontalLayout0.m_PlayerNameText"));

		m_BestLapText = TextWidget.Cast(root.FindWidget("HorizontalLayout0.m_BestLapText"));

		m_CurrentLapText = TextWidget.Cast(root.FindWidget("HorizontalLayout0.m_CurrentLapText"));

		return true;
	}
}
